name: $project_name
main: ${artifact_group}.KotlinForNukkit
version: $project_version
api: ["1.0.5"]
load: STARTUP
author: $project_author
description: $project_description
website: https://github.com/toby7002/KotlinForNukkit
license: $project_license
