name: KotlinForNukkit
main: dev.toby7002.kotlinfornukkit.KotlinForNukkit
version: $version
api: ["1.0.5"]
load: STARTUP
author: toby7002
description: Used to develop plugins with Kotlin
website: https://github.com/toby7002/KotlinForNukkit
